/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:332888:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  mySerial.write("h");
  text("Press any key when Complete",200,350);
  
} //_CODE_:button1:332888:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Smart Attendance");
  button1 = new GButton(this, 265, 160, 282, 78);
  button1.setText("DOWNLOAD DATA");
  button1.setTextBold();
  button1.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  
  label1 = new GLabel(this, 200, 387, 400, 70);
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GLabel label1; 